### ISSUE TITLE
Invalid video links

### ISSUE THREAD

**Issue by YonghaoLong** [CheddarChoi/surch-dataset#1]
Hi,

Thanks a lot for the nice work and the great contribution on the dataset. It is really useful and I am very interested in your work.

Unfortunately, when I am downloading the dataset, there are some links appear to be invalid.

For your reference, below is the invalid video list:
['video009.mp4', 'video017.mp4', 'video018.mp4', 'video042.mp4', 'video068.mp4', 'video098.mp4', 'video099.mp4', 'video100.mp4', 'video101.mp4', 'video102.mp4', 'video103.mp4', 'video104.mp4', 'video105.mp4', 'video106.mp4', 'video115.mp4']

Is there anyway to recover them?

Thanks!

**Comment by CheddarChoi** [comment]
Hi, thank you for reaching out to the Surch dataset!
We've recently re-crawled the video data, but unfortunately, the videos you mentioned have been set to private and we couldn't include them in the dataset. We're exploring options to recover them, but I'm sorry that they are not available now. If you have any further questions, please don't hesitate to reach out!

**Comment by YonghaoLong** [comment]
Thanks！
